{ controlNo: 'CN-1', lastName: 'Abordo', firstName: 'Rose Mary', middleName: 'Visto', sex: 'F', cs: 'M', age: 69, dob: '3/28/1955' },
    { controlNo: 'CN-2', lastName: 'Aguirra', firstName: 'Ma. Julia', middleName: 'Andicoy', sex: 'F', cs: 'M', age: 69, dob: '1/10/1955' },
    { controlNo: 'CN-3', lastName: 'Aguirra', firstName: 'Nestor', middleName: 'Plaza', sex: 'M', cs: 'M', age: 65, dob: '11/10/1958' },
    { controlNo: 'CN-4', lastName: 'Aguirra', firstName: 'Gloria', middleName: 'Delgado', sex: 'F', cs: 'M', age: 60, dob: '4/17/1964' },
  { controlNo: 'CN-5', lastName: 'Allesa', firstName: 'Diocelia', middleName: 'Ambid', sex: 'F', cs: 'W', age: 61, dob: '19/3/1960' },
  { controlNo: 'CN-6', lastName: 'Alongongan', firstName: 'Rosalina', middleName: 'Teruel', sex: 'F', cs: 'W', age: 95, dob: '7/2/1929' },
  { controlNo: 'CN-7', lastName: 'Alongongan', firstName: 'Romulo', middleName: 'Teruel', sex: 'M', cs: 'M', age: 65, dob: '3/10/1959' },
  { controlNo: 'CN-8', lastName: 'Alongongan', firstName: 'Joel', middleName: 'Teruel', sex: 'M', cs: 'Sep', age: 60, dob: '10/3/1963' },
  { controlNo: 'CN-9', lastName: 'Ambid', firstName: 'Bias', middleName: 'Alloso', sex: 'F', cs: 'M', age: 93, dob: '2/3/1931' },
  { controlNo: 'CN-10', lastName: 'Ambid', firstName: 'Leonisa', middleName: 'Alloso', sex: 'F', cs: 'W', age: 100, dob: '2/4/1924' },
  { controlNo: 'CN-11', lastName: 'Ambid', firstName: 'Ricarda', middleName: 'Miranda', sex: 'F', cs: 'M', age: 84, dob: '7/20/1940' },
  { controlNo: 'CN-12', lastName: 'Ambid', firstName: 'Lucibita', middleName: 'Alibocboc', sex: 'F', cs: 'M', age: 77, dob: '4/13/1947' },
  { controlNo: 'CN-13', lastName: 'Ambid', firstName: 'Josefina', middleName: 'Amboy', sex: 'F', cs: 'S', age: 70, dob: '6/19/1954' },
  { controlNo: 'CN-14', lastName: 'Ambid', firstName: 'Mercidita', middleName: 'Amboy', sex: 'F', cs: 'S', age: 67, dob: '4/13/1957' },
  { controlNo: 'CN-15', lastName: 'Ambid', firstName: 'Diego', middleName: 'Amboy', sex: 'M', cs: 'M', age: 76, dob: '11/11/1947' },
  { controlNo: 'CN-16', lastName: 'Ambid', firstName: 'Julio', middleName: 'Amboy', sex: 'M', cs: 'M', age: 60, dob: '1/7/1960' },
  { controlNo: 'CN-17', lastName: 'Arriboy', firstName: 'Enriqueta', middleName: 'Alongonan', sex: 'F', cs: 'W', age: 88, dob: '10/6/1935' },
  { controlNo: 'CN-18', lastName: 'Amboy', firstName: 'Eduardo', middleName: 'Hisugan', sex: 'M', cs: 'W', age: 73, dob: '10/20/1950' },
  { controlNo: 'CN-19', lastName: 'Amboy', firstName: 'Efren Sr', middleName: 'Gonzaga', sex: 'M', cs: 'M', age: 68, dob: '2/1/1956' },
  { controlNo: 'CN-20', lastName: 'Amboy', firstName: 'Luis', middleName: 'Aloggoan', sex: 'M', cs: 'M', age: 68, dob: '6/21/1956' },
  { controlNo: 'CN-21', lastName: 'Amboy', firstName: 'Shirley', middleName: 'Canaway', sex: 'M', cs: 'S', age: 66, dob: '9/22/1957' },
  { controlNo: 'CN-22', lastName: 'Amboy', firstName: 'Lorna', middleName: 'Lladones', sex: 'F', cs: 'W', age: 60, dob: '9/13/1963' },
  { controlNo: 'CN-23', lastName: 'Amboy', firstName: 'Jeanie', middleName: 'Hisogan', sex: 'F', cs: 'M', age: 60, dob: '11/30/1963' },
  { controlNo: 'CN-24', lastName: 'Amparo', firstName: 'Clarita', middleName: 'Alobin', sex: 'F', cs: 'W', age: 88, dob: '1/8/1936' },
  { controlNo: 'CN-25', lastName: 'Amparo', firstName: 'Edgar', middleName: 'Alobin', sex: 'M', cs: 'W', age: 61, dob: '23/4/1960' },
  { controlNo: 'CN-26', lastName: 'Anecita', firstName: 'Norma', middleName: 'Boglosa', sex: 'F', cs: 'M', age: 67, dob: '1/6/1957' },
  { controlNo: 'CN-27', lastName: 'Anecita', firstName: 'Charlie Sr.', middleName: 'Andica', sex: 'M', cs: 'M', age: 70, dob: '12/9/1953' },
  { controlNo: 'CN-28', lastName: 'Anecita', firstName: 'Quintin Jr.', middleName: 'Andica', sex: 'M', cs: 'W', age: 79, dob: '7/27/1945' },
  { controlNo: 'CN-29', lastName: 'Anecita', firstName: 'Rizalita', middleName: 'Visto', sex: 'F', cs: 'M', age: 67, dob: '2/3/1957' },
  { controlNo: 'CN-30', lastName: 'Anecita', firstName: 'Haide', middleName: 'Andica', sex: 'F', cs: 'S', age: 64, dob: '10/26/1959' },
  { controlNo: 'CN-31', lastName: 'Angaray', firstName: 'Ma. Nelita', middleName: 'Gancia', sex: 'F', cs: 'M', age: 73, dob: '5/23/1951' },
  { controlNo: 'CN-32', lastName: 'Angaray', firstName: 'Remedios', middleName: 'Hisugan', sex: 'F', cs: 'M', age: 71, dob: '10/1/1952' },
  { controlNo: 'CN-33', lastName: 'Angaray', firstName: 'Eriberto', middleName: 'Antenorio', sex: 'M', cs: 'M', age: 74, dob: '10/19/1949' },
  { controlNo: 'CN-34', lastName: 'Angaray', firstName: 'Julio', middleName: '', sex: 'M', cs: 'S', age: 80, dob: '7/30/1944' },
  { controlNo: 'CN-35', lastName: 'Atundag', firstName: 'Jose', middleName: 'Ambid', sex: 'M', cs: 'M', age: 66, dob: '12/26/1957' },
  { controlNo: 'CN-36', lastName: 'Atondag', firstName: 'Nedina', middleName: 'Ambid', sex: 'F', cs: 'S', age: 65, dob: '1/12/1959' },
  { controlNo: 'CN-37', lastName: '', firstName: '', middleName: '', sex: 'M', cs: '', age: 60, dob: '16/09/1960' },
  { controlNo: 'CN-38', lastName: 'Camus', firstName: 'Presentacion', middleName: 'Alibagon', sex: 'F', cs: 'W', age: 91, dob: '11/28/1932' },
  { controlNo: 'CN-39', lastName: 'Canaway', firstName: 'Ceferino', middleName: 'Campoid', sex: 'M', cs: 'M', age: 64, dob: '2/5/1960' },
  { controlNo: 'CN-40', lastName: 'Canaway', firstName: 'Susan', middleName: 'Amboy', sex: 'F', cs: 'M', age: 60, dob: '31/08/1960' },
  { controlNo: 'CN-41', lastName: 'Carmelita', firstName: 'Lourdes', middleName: 'Paraon', sex: 'F', cs: 'M', age: 76, dob: '8/9/1947' },
  { controlNo: 'CN-42', lastName: 'Carmelita', firstName: 'Quirico', middleName: 'Marfel', sex: 'M', cs: '', age: 68, dob: '4/24/1956' },
  { controlNo: 'CN-43', lastName: 'Carmelita', firstName: 'Arturo', middleName: 'Marfel', sex: 'M', cs: 'M', age: 60, dob: '4/19/1964' },
  { controlNo: 'CN-44', lastName: 'Cataluña', firstName: 'Rodrigo', middleName: 'Pasole', sex: 'M', cs: 'S', age: 63, dob: '6/12/1969' },
  { controlNo: 'CN-45', lastName: 'Cortez', firstName: 'Emily', middleName: 'Tritin', sex: 'F', cs: 'M', age: 68, dob: '6/15/1956' },
  { controlNo: 'CN-46', lastName: 'Cortez', firstName: 'Burt', middleName: 'Alcubilla', sex: 'M', cs: 'M', age: 66, dob: '5/14/1958' },
  { controlNo: 'CN-47', lastName: 'Cortez', firstName: 'Teofilo', middleName: 'Anitojen', sex: 'M', cs: 'M', age: 78, dob: '12/13/1945' },
  { controlNo: 'CN-48', lastName: 'Cortez', firstName: 'Nelson', middleName: 'Anitojen', sex: 'M', cs: 'S', age: 62, dob: '15/1/1959' },
  { controlNo: 'CN-49', lastName: 'Elumba', firstName: 'Ninfa', middleName: 'Aguirra', sex: 'F', cs: 'M', age: 60, dob: '11/1/1962' },
  { controlNo: 'CN-50', lastName: 'Enriquez', firstName: 'Manuel', middleName: 'Sisma', sex: 'M', cs: '', age: 87, dob: '12/12/1936' },
  { controlNo: 'CN-51', lastName: 'Gancia', firstName: 'Florita', middleName: 'Alobin', sex: 'F', cs: 'W', age: 90, dob: '10/27/1933' },
  { controlNo: 'CN-52', lastName: 'Gancia', firstName: 'Delia', middleName: 'Sanquillos', sex: 'F', cs: 'M', age: 71, dob: '8/12/1952' },
  { controlNo: 'CN-53', lastName: 'Gancia', firstName: 'Jennis', middleName: 'Aguirre', sex: 'M', cs: 'M', age: 67, dob: '11/19/1956' },
  { controlNo: 'CN-54', lastName: 'Gancia', firstName: 'Gerry', middleName: 'Alongongan', sex: 'M', cs: 'M', age: 67, dob: '12/1/1956' },
  { controlNo: 'CN-55', lastName: 'Gancia', firstName: 'Roberto', middleName: 'Aguirre', sex: 'M', cs: 'M', age: 60, dob: '6/7/1959' },
  { controlNo: 'CN-56', lastName: 'Gancia', firstName: 'Nonato', middleName: 'Aguirre', sex: 'M', cs: 'M', age: 71, dob: '6/10/1953' },
  { controlNo: 'CN-57', lastName: 'Gancia', firstName: 'Zenaida', middleName: 'Piojo', sex: 'F', cs: 'M', age: 65, dob: '12/7/1958' },
  { controlNo: 'CN-58', lastName: 'Gancia', firstName: 'Juanito', middleName: 'Aguirre', sex: 'M', cs: 'M', age: 62, dob: '7/4/1962' },
  { controlNo: 'CN-59', lastName: 'Hisugan', firstName: 'Pilar', middleName: 'Gonzaga', sex: 'F', cs: 'M', age: 97, dob: '10/12/1926' },
  { controlNo: 'CN-60', lastName: 'Hisugan', firstName: 'Paulino', middleName: 'Gonzaga', sex: 'M', cs: 'W', age: 61, dob: '29/04/1959' },
  { controlNo: 'CN-61', lastName: 'Hisogan', firstName: 'Ramon', middleName: 'Gonzaga', sex: 'M', cs: 'M', age: 64, dob: '9/1/1956' },
  { controlNo: 'CN-62', lastName: 'Hisogan', firstName: 'Imelda', middleName: 'Salabsalo', sex: 'F', cs: 'M', age: 62, dob: '22/09/1959' },
  { controlNo: 'CN-63', lastName: 'Liabanes', firstName: 'Marilyn Carmelita', middleName: '', sex: 'F', cs: 'W', age: 61, dob: '6/3/1961' },
  { controlNo: 'CN-64', lastName: 'Laurente', firstName: 'Teresita', middleName: 'Alongonan', sex: 'F', cs: 'M', age: 74, dob: '2/10/1950' },
  { controlNo: 'CN-65', lastName: 'Laurente', firstName: 'Loreto', middleName: 'Albancia', sex: 'M', cs: 'M', age: 75, dob: '12/6/1948' },
  { controlNo: 'CN-66', lastName: 'Madero', firstName: 'Juan Elberto', middleName: 'Gonzales', sex: 'M', cs: 'M', age: 60, dob: '15/12/1960' },
  { controlNo: 'CN-67', lastName: 'Madero', firstName: 'Hey June', middleName: 'Macaya', sex: 'M', cs: 'S', age: 60, dob: '7/14/1962' },
  { controlNo: 'CN-68', lastName: 'Madero', firstName: 'Daniel Jr.', middleName: 'Macaya', sex: 'M', cs: 'M', age: 60, dob: '11/21/1963' },
  { controlNo: 'CN-69', lastName: 'Plaza', firstName: 'Shirley', middleName: 'Amboy', sex: 'F', cs: 'S', age: 60, dob: '24/4/1957' },
  { controlNo: 'CN-70', lastName: 'Plaza', firstName: 'Francisco', middleName: 'AMboy', sex: 'M', cs: 'M', age: 60, dob: '1/15/1964' },
  { controlNo: 'CN-71', lastName: 'Salarda', firstName: 'Norberto', middleName: 'Ambid', sex: 'M', cs: 'M', age: 65, dob: '6/5/1957' },
  { controlNo: 'CN-72', lastName: 'Salarda', firstName: 'Marilou', middleName: 'Amid', sex: 'F', cs: 'M', age: 68, dob: '9/3/1956' },
  { controlNo: 'CN-73', lastName: 'Sampedro', firstName: 'Melissa', middleName: 'Piojo', sex: 'F', cs: 'M', age: 70, dob: '4/25/1954' },
  { controlNo: 'CN-74', lastName: 'Sampedro', firstName: 'Emilio', middleName: 'Piojo', sex: 'M', cs: 'M', age: 60, dob: '3/1/1963' },
  { controlNo: 'CN-75', lastName: 'Soltiza', firstName: 'Jemilyn', middleName: 'Macagula', sex: 'F', cs: 'W', age: 65, dob: '7/18/1958' },
  { controlNo: 'CN-76', lastName: 'Soltiza', firstName: 'Jose Luis', middleName: 'Sulo', sex: 'M', cs: 'M', age: 60, dob: '6/25/1963' },
  { controlNo: 'CN-77', lastName: 'Uban', firstName: 'Pancita', middleName: 'Valencia', sex: 'F', cs: 'M', age: 76, dob: '8/2/1948' },
  { controlNo: 'CN-78', lastName: 'Uban', firstName: 'Maximo', middleName: 'Amboy', sex: 'M', cs: 'M', age: 74, dob: '6/28/1950' },
  { controlNo: 'CN-79', lastName: 'Uban', firstName: 'Richard', middleName: 'Piojo', sex: 'M', cs: 'S', age: 64, dob: '7/4/1960' },
  { controlNo: 'CN-80', lastName: 'Uban', firstName: 'Emily', middleName: 'Amboy', sex: 'F', cs: 'S', age: 67, dob: '5/12/1957' },
  { controlNo: 'CN-81', lastName: 'Uban', firstName: 'Danny', middleName: 'Sulo', sex: 'M', cs: 'M', age: 70, dob: '9/13/1954' },
  { controlNo: 'CN-82', lastName: 'Usman', firstName: 'Rufina', middleName: 'Piocom', sex: 'F', cs: 'M', age: 80, dob: '3/21/1944' },
  { controlNo: 'CN-83', lastName: 'Usman', firstName: 'Rubia', middleName: 'Gonzaga', sex: 'F', cs: 'S', age: 60, dob: '7/8/1963' },
  { controlNo: 'CN-84', lastName: 'Veloso', firstName: 'Nicasio', middleName: 'Torrilla', sex: 'M', cs: 'M', age: 70, dob: '4/18/1954' },
  { controlNo: 'CN-85', lastName: 'Veloso', firstName: 'Joseph', middleName: 'Borja', sex: 'M', cs: 'M', age: 62, dob: '8/9/1962' },
  { controlNo: 'CN-86', lastName: 'Zaldivar', firstName: 'Lucia', middleName: 'Tolentino', sex: 'F', cs: 'M', age: 60, dob: '9/6/1963' },
  { controlNo: 'CN-87', lastName: 'Zaldivar', firstName: 'Roberto', middleName: 'Borgas', sex: 'M', cs: 'M', age: 61, dob: '5/24/1963' }
