"""empty message

Revision ID: b323e9d14499
Revises: 
Create Date: 2025-04-03 01:14:34.762353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b323e9d14499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pensioners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('senior_citizen_id', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('civil_status', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('valid_id', sa.String(length=255), nullable=True),
    sa.Column('payout_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('senior_citizen_id')
    )
    op.create_table('schedule_payout',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('payout_date', sa.DateTime(), nullable=True),
    sa.Column('payout_location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pensioner_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pensioner_id'], ['pensioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_pensioner_id'), ['pensioner_id'], unique=False)

    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pensioner_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('payout_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pensioner_id'], ['pensioners.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule_payout.schedule_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_history')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_pensioner_id'))

    op.drop_table('notifications')
    op.drop_table('schedule_payout')
    op.drop_table('pensioners')
    op.drop_table('admin')
    # ### end Alembic commands ###
